{
 "title": "Ressource Usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"node-exporter.monitoring.svc.cluster.local:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"} - node_memory_Cached_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"} - node_memory_Buffers_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter.monitoring.svc.cluster.local:9100\", job=\"node-exporter\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Traffik",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"node-exporter.monitoring.svc.cluster.local:9100\"}[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node-exporter\",instance=\"node-exporter.monitoring.svc.cluster.local:9100\"}[5m])",
     "legendFormat": "{{device}}transmit"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"node-exporter.monitoring.svc.cluster.local:9100\", device!=\"tmpfs\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Used Disc Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\", instance=\"node-exporter.monitoring.svc.cluster.local:9100\", device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"node-exporter.monitoring.svc.cluster.local:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}