apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress
  namespace: wordpress
spec:
#  host: "wordpress.apps.microshift.lab"
  to:
    kind: Service
    name: wordpress
    weight: 100
  port:
    targetPort: 8080
