apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-exporter-privileged
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: node-exporter
    namespace: monitoring

