apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
          - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "admin"
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
          - name: GF_SERVER_ROOT_URL
            value: "/"
          - name: GF_SERVER_SERVE_FROM_SUB_PATH
            value: "true"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 1Gi
        volumeMounts:
          - name: grafana-datasource
            mountPath: /etc/grafana/provisioning/datasources
          - name: grafana-dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards
          - name: grafana-dashboard
            mountPath: /etc/grafana/dashboards
          - name: grafana-data
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard
        - name: grafana-data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: observability
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: "Imported"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/dashboards

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: web
  selector:
    app: grafana
    
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: observability
spec:
  to:
    kind: Service
    name: grafana
  port:
    targetPort: web
  tls:
    termination: edge
