apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-dirs
          image: busybox:latest
          command:
            - sh
            - -c
            - mkdir -p /loki/chunks /loki/index /loki/cache /loki/compactor && chmod -R 777 /loki
          volumeMounts:
            - name: loki-data
              mountPath: /loki
      containers:
        - name: loki
          image: grafana/loki:latest
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: observability
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: info

    common:
      path_prefix: /loki
      ring:
        kvstore:
          store: inmemory
      replication_factor: 1

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/cache
      filesystem:
        directory: /loki/chunks

    schema_config:
      configs:
        - from: 2025-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /loki/compactor
      retention_enabled: true
      retention_delete_delay: 0s
      delete_request_store: filesystem

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 48h
      allow_structured_metadata: true

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: loki
