apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
stringData:
  runner-registration-token: "glrt-s5my5hblAb6id8yiyFfapm86MQpwOjFhbDhzcQp0OjMKdTpqeDRpcxg.01.1j06zh7s2"
