---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab
spec:
  encryptedData:
    runner-token: AgDU0i7ctmNzJAV/kS0N7jHmBL3yUcgBqTb9lP/Mq4PB2nx3GEspZSe9UeIxQICfaEOHz56nlZok4+CdcSTAyhulOiGumW7/GpiGYOADQYJMCT0ScAaW1ldPbpQ7jcRUj2sKXbu2WXVxAW9EVgLtttnRFI9DnqY5JceGKfn+gabskk+PO3HFJQKewVMO6RMobehbmqGjyzZb/5p+3VnTOHHU1FNnGE0GjtjWOexcFDhGXl5HdZkb5zgsBT1oFH6MZYmyuSisDVxbJivQUykDK1jXWwczqdL1Dip2vY1+lw6BE9gljZgKcVpbYoC3rrsmTbdw4sD7u7b+1iRiqR5DzoWLg9aWO1wp3jNm/AlIIvrQHxXzabhGEZI2fFPreuQQGYlKFb3Sn37+yGV5hwQvPvg+A6PWeGRE5k2Kk2ByqYeA4p5OUC476Za5LiFy6rWjSNnHuUZMBq2EMOjPkNLudszfZwHkuNDyueqPlSSdF4zzyO/dl9XdH4LX9jAkGtj7GGIx5E9qCh17PyTX2HG9ddK4au7q4QYIZp258iu2WylQ9BsD1qN0ie8AGQ6utrk0hFuk9AQxAN0kW0HcEoVHbAtYSxDUbYsTXel8MF+xRIx4eYjX68lwcGCqMylTPHjqu5GgPbyePWZpcwoj54UzieHBVfKeiScO/AquPszy2IUrebWWnrUnKSsAaQNv2/AmFyh5kWMAoocOhk60aWhYBy3RJMBRg/g6grDp+NZFMUaBXw124ogvvSFxQx2onkqoJB1i+3Hn1TTkK9Ktigx/j/Fq+dUMkgGx8BwR
  template:
    metadata:
      name: gitlab-runner-secret
      namespace: gitlab
