apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner
  namespace: gitlab
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/exec
    - pods/log
    - services
    - secrets
    - configmaps
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources:
    - deployments
  verbs: ["get", "list", "watch"]

