apiVersion: v1
kind: Pod
metadata:
  name: runner-test
  namespace: gitlab
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: runner
    image: docker.io/gitlab/gitlab-runner:latest
    command: ["sleep"]
    args: ["3600"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never

