apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-console
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/headii/k8s_deplyments.git
    targetRevision: main
    path: deployments/openshift-console
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
